#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin, adapted to esbuild.
# Build: host half via esbuild JS API (bundle src/index.ts → lib/index.js),
#        client half via tsdown (bundle src/client → lib/client.js).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness" "$HOME/deepseek-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

# esbuild 包目录（pnpm store 内任一版本都行；取最高版本，用 node 解析避免 find 路径怪癖）
ESBUILD_PKG="$(node -e "
const fs = require('fs');
const p = process.argv[1];
const store = p + '/node_modules/.pnpm';
const dirs = fs.existsSync(store) ? fs.readdirSync(store).filter(d => d.startsWith('esbuild@')) : [];
if (!dirs.length) process.exit(1);
const top = dirs.sort().pop();
process.stdout.write(store + '/' + top + '/node_modules/esbuild');
" "$CHECKOUT" 2>/dev/null)" || true
if [ -z "$ESBUILD_PKG" ]; then
  ESBUILD_PKG="$(find "$CHECKOUT/node_modules" -maxdepth 3 -type d -name 'esbuild' 2>/dev/null | head -1)"
fi
if [ -z "$ESBUILD_PKG" ] || [ ! -f "$ESBUILD_PKG/lib/main.js" ]; then
  echo "build: esbuild not found under $CHECKOUT" >&2
  exit 1
fi

export ESBUILD_PKG
echo "=== Building host (esbuild via $ESBUILD_PKG) ==="
node scripts/build-host.mjs || exit 1

echo "=== Building client (tsdown) ==="
npm run build:client || exit 1

echo "=== Build complete ==="